[package]
name = "lunatic-sqlite-api"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
sqlite = "0.27.0"
wasmtime = "^1" # managed by root Cargo.toml
hash-map-id = { version = "^0.10", path = "../hash-map-id" }
lunatic-common-api = { version = "^0.10", path = "../lunatic-common-api" }
lunatic-error-api = { version = "^0.10", path = "../lunatic-error-api" }
lunatic-process = { version = "^0.10", path = "../lunatic-process" }